name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@5.1
      with:
        cli: 1.10.3.929
        lein: 2.9.1
    - name: Run Clojure tests
      run: lein test
  deploy:
    runs-on: ubuntu-latest
    needs: unit-tests
    steps:
    - uses: actions/checkout@v3
    - name: Deploy to Heroku
      uses: akhileshns/heroku-deploy@v3.12.12
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "morning-inlet-68068"
        heroku_email: "tim@richardt.io"
  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
    - uses: actions/checkout@v3
    - name: Run E2E tests
      run: |
        chmod +x "${GITHUB_WORKSPACE}/test/e2e_tests.sh"
        bash +x "${GITHUB_WORKSPACE}/test/e2e_tests.sh"