name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Clojure
      uses: DeLaGuardo/setup-clojure@5.1
      with:
        cli: 1.10.3.929
        lein: 2.9.1
    - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: "morning-inlet-68068"
        heroku_email: "tim@richardt.io"